// ការប្រើប្រាស់ Path ផ្ទាល់ពី public/music/
export const MOCK_SONGS = [
   
  // ALBUMS-1
  {
    id: '001',
    number: '001',
    title: 'BEAT (1)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '3 MINUTES 45 SECONDS',
    price: 0.25,
    coverUrl: '/lg1.png',
    audioUrl: '/music/beat-1.mp3', // ត្រូវប្រាកដថាឈ្មោះ File ក្នុង Folder ត្រូវគ្នា
  },
    {
    id: '002',
    number: '002',
    title: 'BEAT (2)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 20 SECONDS',
    price: 0.25,
    coverUrl: '/lg1.png',
    audioUrl: '/music/beat-2.mp3', 
  },
      {
    id: '003',
    number: '003',
    title: 'BEAT (3)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 20 SECONDS',
    price: 0.25,
    coverUrl: '/lg1.png',
    audioUrl: '/music/beat-3.mp3', 
  },
        {
    id: '004',
    number: '004',
    title: 'BEAT (4)',
    releaseDate: 'JHigh Quality',
    type: 'SINGLE, 1 SONG',
    duration: '3 MINUTES 18 SECONDS',
    price: 0.25,
    coverUrl: '/lg1.png',
    audioUrl: '/music/beat-4.mp3', 
  },

   // ALBUMS-2
  {
    id: '005',
    number: '005',
    title: 'BEAT (5)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 27 SECONDS',
    price: 0.25,
    coverUrl: '/lg2.png',
    audioUrl: '/music/beat-5.mp3', 
  },
    {
    id: '006',
    number: '006',
    title: 'BEAT (6)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 22 SECONDS',
    price: 0.25,
    coverUrl: '/lg2.png',
    audioUrl: '/music/beat-6.mp3', 
  },
      {
    id: '007',
    number: '007',
    title: 'BEAT (7)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 10 SECONDS',
    price: 0.25,
    coverUrl: '/lg2.png',
    audioUrl: '/music/beat-7.mp3', 
  },
        {
    id: '008',
    number: '008',
    title: 'BEAT (8)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '4 MINUTES 14 SECONDS',
    price: 0.25,
    coverUrl: '/lg2.png',
    audioUrl: '/music/beat-8.mp3', 
  },
  {
    id: '009',
    number: '009',
    title: 'BEAT (9)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '5 MINUTES 00 SECONDS',
    price: 0.00,
    coverUrl: '/lg2.png',
    audioUrl: '/music/beat-9.mp3', 
  },

  // ALBUMS-3
  {
    id: '010',
    number: '010',
    title: 'BEAT (10)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-10.mp3', 
  },
  {
    id: '011',
    number: '011',
    title: 'BEAT (11)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-11.mp3', 
  },
  {
    id: '012',
    number: '012',
    title: 'BEAT (12)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-12.mp3', 
  },
  {
    id: '013',
    number: '013',
    title: 'BEAT (13)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-13.mp3', 
  },
  {
    id: '014',
    number: '014',
    title: 'BEAT (14)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-14.mp3', 
  },
  {
    id: '015',
    number: '015',
    title: 'BEAT (15)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-15.mp3', 
  },
  {
    id: '016',
    number: '016',
    title: 'BEAT (16)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-16.mp3', 
  },
  {
    id: '017',
    number: '017',
    title: 'BEAT (17)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-17.mp3', 
  },
    {
    id: '018',
    number: '018',
    title: 'BEAT (18)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-18.mp3', 
  },
    {
    id: '019',
    number: '019',
    title: 'BEAT (19)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-19.mp3', 
  },
    {
    id: '020',
    number: '020',
    title: 'BEAT (20)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-20.mp3', 
  },
    {
    id: '021',
    number: '021',
    title: 'BEAT (21)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-21.mp3', 
  },
    {
    id: '022',
    number: '022',
    title: 'BEAT (22)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-22.mp3', 
  },
    {
    id: '023',
    number: '023',
    title: 'BEAT (23)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-23.mp3', 
  },
    {
    id: '024',
    number: '024',
    title: 'BEAT (24)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-24.mp3', 
  },
    {
    id: '025',
    number: '025',
    title: 'BEAT (25)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-25.mp3', 
  },
    {
    id: '026',
    number: '026',
    title: 'BEAT (26)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-26.mp3', 
  },
    {
    id: '027',
    number: '027',
    title: 'BEAT (27)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-27.mp3', 
  },
    {
    id: '028',
    number: '028',
    title: 'BEAT (28)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-28.mp3', 
  },
    {
    id: '029',
    number: '029',
    title: 'BEAT (29)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-29.mp3', 
  },
    {
    id: '030',
    number: '030',
    title: 'BEAT (30)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-30.mp3', 
  },
    {
    id: '031',
    number: '031',
    title: 'BEAT (31)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-31.mp3', 
  },
    {
    id: '032',
    number: '032',
    title: 'BEAT (32)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-32.mp3', 
  },
    {
    id: '033',
    number: '033',
    title: 'BEAT (33)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-33.mp3', 
  },
    {
    id: '034',
    number: '034',
    title: 'BEAT (34)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-34.mp3', 
  },
    {
    id: '035',
    number: '035',
    title: 'BEAT (35)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-35.mp3', 
  },
    {
    id: '036',
    number: '036',
    title: 'BEAT (36)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-36.mp3', 
  },
    {
    id: '037',
    number: '037',
    title: 'BEAT (37)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-37.mp3', 
  },
    {
    id: '038',
    number: '038',
    title: 'BEAT (38)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-38.mp3', 
  },
    {
    id: '039',
    number: '039',
    title: 'BEAT (39)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-39.mp3', 
  },
    {
    id: '040',
    number: '040',
    title: 'BEAT (40)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-40.mp3', 
  },
    {
    id: '041',
    number: '041',
    title: 'BEAT (41)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-41.mp3', 
  },
    {
    id: '042',
    number: '042',
    title: 'BEAT (42)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-42.mp3', 
  },
    {
    id: '043',
    number: '043',
    title: 'BEAT (43)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-43.mp3', 
  },
    {
    id: '044',
    number: '044',
    title: 'BEAT (44)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-44.mp3', 
  },
    {
    id: '045',
    number: '045',
    title: 'BEAT (45)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-45.mp3', 
  },
    {
    id: '046',
    number: '046',
    title: 'BEAT (46)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-46.mp3', 
  },
    {
    id: '047',
    number: '047',
    title: 'BEAT (47)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-47.mp3', 
  },
    {
    id: '048',
    number: '048',
    title: 'BEAT (48)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-48.mp3', 
  },
    {
    id: '049',
    number: '049',
    title: 'BEAT (49)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-49.mp3', 
  },
    {
    id: '050',
    number: '050',
    title: 'BEAT (50)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-50.mp3', 
  },
    {
    id: '051',
    number: '051',
    title: 'BEAT (51)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-51.mp3', 
  },
    {
    id: '052',
    number: '052',
    title: 'BEAT (52)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-52.mp3', 
  },
    {
    id: '053',
    number: '053',
    title: 'BEAT (53)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-53.mp3', 
  },
    {
    id: '054',
    number: '054',
    title: 'BEAT (54)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-54.mp3', 
  },
    {
    id: '055',
    number: '055',
    title: 'BEAT (55)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-55.mp3', 
  },
    {
    id: '056',
    number: '056',
    title: 'BEAT (56)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-56.mp3', 
  },
    {
    id: '057',
    number: '057',
    title: 'BEAT (57)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-57.mp3', 
  },
    {
    id: '058',
    number: '058',
    title: 'BEAT (58)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-58.mp3', 
  },
    {
    id: '059',
    number: '059',
    title: 'BEAT (59)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-59.mp3', 
  },
    {
    id: '060',
    number: '060',
    title: 'BEAT (60)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-60.mp3', 
  },
    {
    id: '061',
    number: '061',
    title: 'BEAT (61)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-61.mp3', 
  },
    {
    id: '062',
    number: '062',
    title: 'BEAT (62)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-62.mp3', 
  },
    {
    id: '063',
    number: '063',
    title: 'BEAT (63)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-63.mp3', 
  },
    {
    id: '064',
    number: '064',
    title: 'BEAT (64)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-64.mp3', 
  },
    {
    id: '065',
    number: '065',
    title: 'BEAT (65)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-65.mp3', 
  },
    {
    id: '066',
    number: '066',
    title: 'BEAT (66)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-66.mp3', 
  },
    {
    id: '067',
    number: '067',
    title: 'BEAT (67)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-67.mp3', 
  },
    {
    id: '068',
    number: '068',
    title: 'BEAT (68)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-68.mp3', 
  },
    {
    id: '069',
    number: '069',
    title: 'BEAT (69)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-69.mp3', 
  },
    {
    id: '070',
    number: '070',
    title: 'BEAT (70)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-70.mp3', 
  },
    {
    id: '071',
    number: '071',
    title: 'BEAT (71)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-71.mp3', 
  },
    {
    id: '072',
    number: '072',
    title: 'BEAT (72)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-72.mp3', 
  },
    {
    id: '073',
    number: '073',
    title: 'BEAT (73)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-73.mp3', 
  },
    {
    id: '074',
    number: '074',
    title: 'BEAT (74)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-74.mp3', 
  },
    {
    id: '075',
    number: '075',
    title: 'BEAT (75)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-75.mp3', 
  },
    {
    id: '076',
    number: '076',
    title: 'BEAT (76)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-76.mp3', 
  },
    {
    id: '077',
    number: '077',
    title: 'BEAT (77)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-77.mp3', 
  },
    {
    id: '078',
    number: '078',
    title: 'BEAT (78)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-78.mp3', 
  },
    {
    id: '079',
    number: '079',
    title: 'BEAT (79)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-79.mp3', 
  },
    {
    id: '080',
    number: '080',
    title: 'BEAT (80)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-80.mp3', 
  },
    {
    id: '081',
    number: '081',
    title: 'BEAT (81)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-81.mp3', 
  },
    {
    id: '082',
    number: '082',
    title: 'BEAT (82)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-82.mp3', 
  },
    {
    id: '083',
    number: '083',
    title: 'BEAT (83)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-83.mp3', 
  },
    {
    id: '084',
    number: '084',
    title: 'BEAT (84)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-84.mp3', 
  },
    {
    id: '085',
    number: '085',
    title: 'BEAT (85)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-85.mp3', 
  },
    {
    id: '086',
    number: '086',
    title: 'BEAT (86)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-86.mp3', 
  },
    {
    id: '087',
    number: '087',
    title: 'BEAT (87)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-87.mp3', 
  },
    {
    id: '088',
    number: '088',
    title: 'BEAT (88)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-88.mp3', 
  },
    {
    id: '089',
    number: '089',
    title: 'BEAT (89)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-89.mp3', 
  },
    {
    id: '090',
    number: '090',
    title: 'BEAT (90)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-90.mp3', 
  },
    {
    id: '091',
    number: '091',
    title: 'BEAT (91)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-91.mp3', 
  },
    {
    id: '092',
    number: '092',
    title: 'BEAT (92)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-92.mp3', 
  },
    {
    id: '093',
    number: '093',
    title: 'BEAT (93)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-93.mp3', 
  },
    {
    id: '094',
    number: '094',
    title: 'BEAT (94)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-94.mp3', 
  },
    {
    id: '095',
    number: '095',
    title: 'BEAT (95)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-95.mp3', 
  },
    {
    id: '096',
    number: '096',
    title: 'BEAT (96)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-96.mp3', 
  },
    {
    id: '097',
    number: '097',
    title: 'BEAT (97)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-97.mp3', 
  },
    {
    id: '098',
    number: '098',
    title: 'BEAT (98)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-98.mp3', 
  },
    {
    id: '099',
    number: '099',
    title: 'BEAT (99)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-99.mp3', 
  },
    {
    id: '100',
    number: '100',
    title: 'BEAT (100)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-100.mp3', 
  },
    {
    id: '101',
    number: '101',
    title: 'BEAT (101)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-101.mp3', 
  },
    {
    id: '102',
    number: '102',
    title: 'BEAT (102)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-102.mp3', 
  },
    {
    id: '103',
    number: '103',
    title: 'BEAT (103)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-103.mp3', 
  },
    {
    id: '104',
    number: '104',
    title: 'BEAT (104)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-104.mp3', 
  },
    {
    id: '105',
    number: '105',
    title: 'BEAT (105)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-105.mp3', 
  },
    {
    id: '106',
    number: '106',
    title: 'BEAT (106)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-106.mp3', 
  },
    {
    id: '107',
    number: '107',
    title: 'BEAT (107)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-107.mp3', 
  },
    {
    id: '108',
    number: '108',
    title: 'BEAT (108)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-108.mp3', 
  },
    {
    id: '109',
    number: '109',
    title: 'BEAT (109)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-109.mp3', 
  },
    {
    id: '110',
    number: '110',
    title: 'BEAT (110)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-110.mp3', 
  },
    {
    id: '111',
    number: '111',
    title: 'BEAT (111)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-111.mp3', 
  },
    {
    id: '112',
    number: '112',
    title: 'BEAT (112)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-112.mp3', 
  },
    {
    id: '113',
    number: '113',
    title: 'BEAT (113)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-113.mp3', 
  },
    {
    id: '114',
    number: '114',
    title: 'BEAT (114)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-114.mp3', 
  },
    {
    id: '115',
    number: '115',
    title: 'BEAT (115)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-red.png',
    audioUrl: '/music/beat-115.mp3', 
  },
    {
    id: '116',
    number: '116',
    title: 'BEAT (116)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-or.png',
    audioUrl: '/music/beat-116.mp3', 
  },
    {
    id: '117',
    number: '117',
    title: 'BEAT (117)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-tikbrak.png',
    audioUrl: '/music/beat-117.mp3', 
  },
    {
    id: '118',
    number: '118',
    title: 'BEAT (118)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-slear.png',
    audioUrl: '/music/beat-118.mp3', 
  },
    {
    id: '119',
    number: '119',
    title: 'BEAT (119)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/icon.png',
    audioUrl: '/music/beat-119.mp3', 
  },
    {
    id: '120',
    number: '120',
    title: 'BEAT (120)-(COMING SOON!)',
    releaseDate: 'High Quality',
    type: 'SINGLE, 1 SONG',
    duration: '0 MINUTES 00 SECONDS',
    price: 0.99,
    coverUrl: '/logo-gold.png',
    audioUrl: '/music/beat-120.mp3', 
  },

];